#!/usr/bin/env python3
from __future__ import annotations

import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from m_c_video_to_robot.paths import isaac_root, relative_to_repo  # noqa: E402
from m_c_video_to_robot.robot_asset import CONTROLLED_JOINT_NAMES, find_official_urdf, parse_urdf  # noqa: E402


def _placeholder(path: Path, root: Path) -> str:
    try:
        return "${MINDBOT_ISAAC_ROOT}/" + path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return relative_to_repo(path)


def _find_files(root: Path, suffixes: tuple[str, ...], max_count: int = 20) -> list[Path]:
    found: list[Path] = []
    for path in root.rglob("*"):
        if path.is_file() and path.suffix.lower() in suffixes:
            found.append(path)
            if len(found) >= max_count:
                break
    return found


def _registered_envs(root: Path) -> list[str]:
    init_file = root / "source/mindbot_isaac_sim/mindbot_isaac_sim/tasks/dual_arm_waist_reach/__init__.py"
    if not init_file.exists():
        return []
    text = init_file.read_text(encoding="utf-8")
    return re.findall(r'id="([^"]+)"', text)


def main() -> None:
    root = isaac_root()
    urdf = find_official_urdf(root)
    spec = parse_urdf(urdf)
    launchers = [p for p in (root / "mindbot_isaaclab.sh", root / "isaaclab.sh", root / "python.sh", root / "isaac-sim.sh") if p.exists()]
    package = root / "source/mindbot_isaac_sim"
    mesh_dirs = sorted({p.parent for p in _find_files(root, (".stl", ".obj", ".dae"), max_count=100)})
    envs = _registered_envs(root)

    lines = [
        "# Official Environment Inventory",
        "",
        "Generated by `./.venv-tools/bin/python scripts/inspect_official_environment.py`.",
        "",
        "## Paths",
        "",
        f"- Isaac root: `${{MINDBOT_ISAAC_ROOT}}`",
        f"- Active robot URDF: `{_placeholder(urdf, root)}`",
        "- Robot USD: not found in the official environment inventory; Isaac Lab converts the URDF at launch.",
        f"- Isaac Lab package/extension: `{_placeholder(package, root)}`" if package.exists() else "- Isaac Lab package/extension: not found",
        "",
        "## Mesh Directories",
        "",
    ]
    lines.extend(f"- `{_placeholder(path, root)}`" for path in mesh_dirs)
    lines.extend(["", "## Launchers", ""])
    lines.extend(f"- `{_placeholder(path, root)}`" for path in launchers)
    lines.extend(["", "## Registered Environments", ""])
    lines.extend(f"- `{env}`" for env in envs)
    lines.extend(["", "## Controlled Joint Order", ""])
    for idx, name in enumerate(CONTROLLED_JOINT_NAMES):
        joint = spec.joints[name]
        limit = joint.limit
        lines.append(
            f"{idx}. `{name}` parent=`{joint.parent}` child=`{joint.child}` "
            f"axis={joint.axis_xyz} default=0.0 "
            f"limit=[{limit.lower}, {limit.upper}] velocity={limit.velocity} effort={limit.effort}"
        )
    lines.extend(
        [
            "",
            "## Default Pose",
            "",
            "The official `dual_arm_waist.py` sets waist, left arm, right arm, and RealSense pitch joints to 0.0 rad.",
            "",
            "## Control Mode",
            "",
            "The official joint-position environment exposes manager action terms `left_arm_action`, `right_arm_action`, `waist_action`, and `realsense_pitch_action`. This project only sends named position targets for `waist_joint` and the twelve arm joints.",
            "",
            "## Existing Replay Code",
            "",
            "The official environment includes deterministic demos in `${MINDBOT_ISAAC_ROOT}/scripts/demo_dual_arm_waist_motion.py` and `${MINDBOT_ISAAC_ROOT}/scripts/demo_end_effector_ik.py`. This repository adds motion-file replay without modifying those demos.",
        ]
    )
    output = REPO_ROOT / "docs/official_environment_inventory.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(relative_to_repo(output))


if __name__ == "__main__":
    main()
